---
title: Perdidos en el Espacio
theme: green
hero_image: images/lost-in-space.png
description: ¡Aprende a programar tu propia animación!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animation, space
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introducción
- title: Animar una nave espacial
- title: Animar usando bucles
- title: Mono flotante
- title: Asteroides que rebotan
- title: Estrellas que brillan
- title: "Desafío: Crea tu propia animación"

