---
title: Perdu dans l'espace
theme: green
hero_image: images/lost-in-space.png
description: Apprends à programmer ta propre animation!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animation, space
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduction
- title: Les lutins
- title: Animez vos lutins
- title: Animez à l'aide de boucles
- title: Plus de boucles
- title: "Défi : Créez votre propre animation"

