---
title: Perduto nello Spazio
theme: green
hero_image: images/lost-in-space.png
description: Impara a programmare la tua animazione!
original_url: https://projects.raspberrypi.org/en/projects/lost-in-space
duration: 2
listed: true
copyedit: true
ingredient: false
curriculum: builder, design-0, programming-1, phys-comp-0, manufacture-0, community-0
interests: animation, space
technologies: scratch
site_areas: codeclub, scratch
steps:
- title: Introduzione
- title: Animare un'astronave
- title: Animare usando i loop
- title: Scimmie Fluttuanti
- title: Asteroidi Rimbalzanti
- title: Stelle Splendenti
- title: "Sfida: Crea la tua animazione"

